spring:
  config:
    activate:
      on-profile: local
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://180.69.253.126:3046/wc
    username: danchu
    password: '0000'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mapper/*.xml

jwt:
  secret: 4oCYbGVhLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtbmZ0LXNwcmluZy1ib290LWp3dC10dXRvcmlhbOKAmQo=

app:
  config:
    file:
      path: /Users/wonjung/Workspace/Intellij/Practice/Be/Upload/

logging:
  config: classpath:log4j2.xml

---

#### DEV CONFIG ####
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://180.69.253.126:3046/wc
    username: danchu
    password: '0000'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mapper/*.xml

jwt:
  secret: 4oCYbGVhLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtbmZ0LXNwcmluZy1ib290LWp3dC10dXRvcmlhbOKAmQo=

app:
  config:
    file:
      path: /Users/wonjung/Workspace/Intellij/Practice/Be/Upload/

logging:
  config: classpath:log4j2.xml

---

#### HOME CONFIG ####
spring:
  config:
    activate:
      on-profile: home
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.45.115:3046/wc
    username: danchu
    password: '0000'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mapper/*.xml

jwt:
  secret: 4oCYbGVhLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtbmZ0LXNwcmluZy1ib290LWp3dC10dXRvcmlhbOKAmQo=

app:
  config:
    file:
      path: /Users/wonjung/Workspace/Intellij/Practice/Be/Upload/

logging:
  config: classpath:log4j2.xml